initial_filter_timeframe: "1d"
signal_filter_timeframe: "30m"
execution_filter_timeframe: "5m"

min_return: 0
min_volume: 10000000

breakout_bars: 144
volume_ma_bars: 144
atr_compression_rank_bars: 144
atr_compression_cutoff: 0.333

donchian_entry_bars: 12

atr_bars: 30
max_leverage: 0.9
min_loss_atr: 3