initial_filter_timeframe: "1d"
signal_filter_timeframe: "30m"
execution_filter_timeframe: "5m"
exit_filter_timeframe: "30m"

min_return: -5
min_volume: 1000000

breakout_bars: 240
breakout_n_atr: 0.5

volume_quantile_bars: 240
volume_quantile: 1

donchian_entry_bars: 12

total_risk: 0.02
max_risk_per_trade: 0.002
entry_atr_stop_multiplier: 1
max_leverage: 1
min_loss_atr: 3