initial_filter_timeframe: "1d"
signal_filter_timeframe: "30m"
execution_filter_timeframe: "5m"

min_return: -5
min_volume: 1000000

breakout_bars: 14
breakout_n_atr: 0.5
volume_ma_bars: 144
atr_compression_rank_bars: 144
atr_compression_cutoff: 0.333

donchian_entry_bars: 12

atr_bars: 30
max_leverage: 0.3
min_loss_atr: 3